-- MySQL Script generated by MySQL Workbench
-- Wed Apr 10 22:22:24 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema GP
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GP` DEFAULT CHARACTER SET utf8 ;
USE `GP` ;

-- -----------------------------------------------------
-- Table `GP`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GP`.`student` (
  `sid` INT NOT NULL,
  `FNAME` VARCHAR(45) NULL,
  `LNAME` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Pasword` VARCHAR(45) NULL,
  PRIMARY KEY (`sid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GP`.`prof`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GP`.`prof` (
  `pid` INT NOT NULL,
  `FNAME` VARCHAR(45) NULL,
  `LNAME` VARCHAR(45) NULL,
  `EMAIL` VARCHAR(45) NULL,
  `PASSWORD` VARCHAR(45) NULL,
  PRIMARY KEY (`pid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GP`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GP`.`course` (
  `cid` INT NOT NULL,
  `CName` VARCHAR(45) NULL,
  `prof_pid` INT NOT NULL,
  PRIMARY KEY (`cid`, `prof_pid`),
  INDEX `fk_course_prof1_idx` (`prof_pid` ASC),
  CONSTRAINT `fk_course_prof1`
    FOREIGN KEY (`prof_pid`)
    REFERENCES `GP`.`prof` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GP`.`student_has_course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GP`.`student_has_course` (
  `student_sid` INT NOT NULL,
  `course_cid` INT NOT NULL,
  PRIMARY KEY (`student_sid`, `course_cid`),
  INDEX `fk_student_has_course_course1_idx` (`course_cid` ASC),
  INDEX `fk_student_has_course_student_idx` (`student_sid` ASC),
  CONSTRAINT `fk_student_has_course_student`
    FOREIGN KEY (`student_sid`)
    REFERENCES `GP`.`student` (`sid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_has_course_course1`
    FOREIGN KEY (`course_cid`)
    REFERENCES `GP`.`course` (`cid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GP`.`class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GP`.`class` (
  `cid` INT NOT NULL,
  `FloorNum` INT NULL,
  `RoomNum` INT NULL,
  PRIMARY KEY (`cid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GP`.`day`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GP`.`day` (
  `did` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`did`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GP`.`period`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GP`.`period` (
  `pid` INT NOT NULL,
  `starttime` time NULL,
  `endtime` time NULL,
  PRIMARY KEY (`pid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GP`.`timetable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GP`.`timetable` (
  `day_did` INT NOT NULL,
  `period_pid` INT NOT NULL,
  `class_cid` INT NOT NULL,
  `course_cid` INT NOT NULL,
  PRIMARY KEY (`class_cid`, `day_did`, `period_pid`,`course_cid`),
  INDEX `fk_timetable_day1_idx` (`day_did` ASC),
  INDEX `fk_timetable_period1_idx` (`period_pid` ASC),
  CONSTRAINT `fk_timetable_class1`
    FOREIGN KEY (`class_cid`)
    REFERENCES `GP`.`class` (`cid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_timetable_day1`
    FOREIGN KEY (`day_did`)
    REFERENCES `GP`.`day` (`did`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_timetable_course1`
    FOREIGN KEY (`course_cid`)
    REFERENCES `GP`.`course` (`cid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_timetable_period1`
    FOREIGN KEY (`period_pid`)
    REFERENCES `GP`.`period` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GP`.`attendance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GP`.`attendance` (
  `student_sid` INT NOT NULL,
  `course_cid` INT NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`student_sid`, `course_cid`,`date`),
  INDEX `fk_attendance_course1_idx` (`course_cid` ASC),
  CONSTRAINT `fk_attendance_student1`
    FOREIGN KEY (`student_sid`)
    REFERENCES `GP`.`student` (`sid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_attendance_course1`
    FOREIGN KEY (`course_cid`)
    REFERENCES `GP`.`course` (`cid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GP`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GP`.`admin` (
  `id` INT NOT NULL,
  `Email` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GP`.`complains`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `GP`.`complains` (
  `complains_student_sid` INT NOT NULL,
  `complains_course_cid` INT NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`complains_student_sid`, `complains_course_cid`, `date`),
  INDEX `fk_complains_complains1_idx` (`complains_student_sid` ASC, `complains_course_cid` ASC),
  CONSTRAINT `fk_complains_student1`
    FOREIGN KEY (`complains_student_sid`)
    REFERENCES `GP`.`student` (`sid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_complains_course1`
    FOREIGN KEY (`complains_course_cid`)
    REFERENCES `GP`.`course` (`cid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `GP` ;

-- -----------------------------------------------------
-- View `GP`.`view1`
-- -----------------------------------------------------
USE `GP`;


-- -----------------------------------------------------
-- View `GP`.`view2`
-- -----------------------------------------------------
USE `GP`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
